# user/fixedstars.py
# uncomment lines / stars you need; included are some common categories
# (stars repeat inside different categories ); save file after modifying
# alphabetical521 should not be directly used : includes all 521 named stars
# and is there so user can find & select stars of interest, then put them
# into 'custom' category

# fixedstars.py: modified fixed stars data file; last modified on 2025-06-23 by aum
# xx, name, flag_result = swe.fixstar2_ut(star, julian_day_ut, flags) -> returns :
# xx = longitude, latitude, distance, long. speed, lat. speed, dist. speed
# name = traditional, nomenclature name; flag_result = flag(s) used

# northern constellations: andromeda | cygnus | pegasus | aquila | delphinus |
# perseus | auriga | draco | sagitta | bootes | equuleus | serpens | cassiopeia |
# hercules | triangulum | cepheus | lyra | ursa major | corona borealis |
# ophiuchus | ursa minor
# southern constellations: ara | cetus | hydra | argo | corona australis | lepus |
# canis major | corvus | lupus | canis minor | crater | orion | centaurus |
# eridanus | piscis australis

FIXEDSTARS = {
    "custom": [
        ("alCMa", "sirius", "096 sirius"),  # 6/27
        # ("bePer", "algol", "01. algol"),  # 3/27
        ("etTau", "krttika", "03 krt krttika"),  # 3/27
        # ("GCLiu", "gcliu", "galactic center (new) (liu/zhu/zhang 2010)"),
    ],
    "naksatras": [  # 28
        ("beAri", "ashvini", "01 asv asvini"),  # sheratan
        ("41Ari", "bharani", "02 bha bharani"),  # /
        ("etTau", "krttika", "03 krt krttika"),  # alcyone
        ("alTau", "rohini", "04 roh rohini"),  # aldebaran
        ("laOri", "mrgashirsha", "05 mrg mrgasira"),  # ??? meissa
        ("alOri", "ardra", "06 ard ardra"),  # betelgeuse
        ("beGem", "punarvasu", "07 pun punarvasu"),  # pollux
        ("deCnc", "pushya", "08 pus pusya"),  # asellus australis
        # ("epHya", "ashlesha", "09 asl aslesa"), # /
        ("alCnc", "aslesa (colebrook)", "09 aslesa (colebrook)"),  # acubens
        ("alLeo", "magha", "10 mag magha"),  # regulus
        ("deLeo", "purvaphalguni", "11 ppa purvaphalguni"),  # zosma
        ("beLeo", "uttaraphalguni", "12 upa uttaraphalguni"),  # denebola
        ("deCrv", "hasta", "13 has hasta"),  # algorab
        ("alVir", "citra", "14 cit chitra"),  # spica todo ???
        ("alBoo", "svati", "15 sva svati"),  # arcturus
        ("io-1Lib", "vishakha", "16 vis visakha"),  # /
        ("deSco", "anuradha", "17 anu anuradha"),  # dschubba
        ("alSco", "jyeshtha", "18 jye jyestha"),  # antares
        ("laSco", "mula", "19 mul mula"),  # ??? shaula
        ("deSgr", "purvashadha", "20 pas purvasadha"),  # kaus media
        ("siSgr", "uttarashadha", "21 uas uttarasadha"),  # nunki, pelagus
        ("alLyr", "abhijit", "22 abh abhijit"),  # vega
        ("alAql", "shravana", "23 sra sravana"),  # altair
        ("beDel", "dhanishtha", "24 dha dhanistha"),  # /
        ("laAqr", "shatabhishak", "25 sat satabhisa"),  # ekkhysis, hydor
        ("alPeg", "purvabhadra", "26 pbh purvabhadra"),  # markab
        ("gaPeg", "uttarabhadra", "27 ubh uttarabhadra"),  # algenib
        ("zePsc", "revati", "28 rev revati"),  # /
    ],
    "behenian": [  # 15
        ("bePer", "algol", "01 algol"),
        ("etTau", "alcyone", "02 alcyone"),
        ("alTau", "aldebaran", "03 aldebaran"),
        ("alAur", "capella", "04 capella"),
        ("alCMa", "sirius", "05 sirius"),
        ("alCMi", "procyon", "06 procyon"),
        ("alLeo", "regulus", "07 regulus"),
        ("etUMa", "alkaid", "08 alkaid"),
        ("deCrv", "algorab", "09 algorab"),
        ("alVir", "spica", "10 spica"),
        ("alBoo", "arcturus", "11 arcturus"),
        ("alCrB", "alphecca", "12 alphecca"),
        ("alSco", "antares", "13 antares"),
        ("alLyr", "vega", "14 vega"),
        ("deCap", "deneb algedi", "15 deneb algedi"),
    ],
}
# below are for orientation only - dont plot 117 nor 521 stars on chart !
# ---
#    "robson": [  # 117
#        ("alEri", "achernar", "001 achernar"),
#        ("alCru", "acrux", "002 acrux"),
#        ("alCnc", "acubens", "003 acubens"),
#        ("M6", "aculeus", "004 aculeus"),
#        ("M7", "acumen", "005 acumen"),
#        ("zeLeo", "adhafera", "006 adhafera"),
#        ("beCen", "agena", "007 agena"),
#        ("be-1Cyg", "albireo", "008 albireo"),
#        ("etTau", "alcyone", "009 alcyone"),
#        ("alTau", "aldebaran", "010 aldebaran"),
#        ("gaPeg", "algenib", "011 algenib"),
#        ("etLeo", "al jabhah", "012 al jabhah, algenubi"),
#        ("bePer", "algol", "013 algol"),
#        ("deCrv", "algorab", "014 algorab"),
#        ("zeTau", "al hecka", "015 al hecka"),
#        ("gaGem", "alhena", "016 alhena"),
#        ("ga-1And", "almach", "017 almach"),
#        ("epOri", "alnilam", "018 alnilam, cingula orionis 1/2"),
#        ("alHya", "alphard", "019 alphard"),
#        ("alCrB", "alphecca", "020 alphecca"),
#        ("alAnd", "alpheratz", "021 alpheratz"),
#        ("etPsc", "al pherg", "022 al pherg"),
#        ("alAql", "altair", "023 altair"),
#        ("alSco", "antares", "024 antares"),
#        ("alBoo", "arcturus", "025 arcturus"),
#        ("etCap", "armus", "026 armus"),
#        ("zeSgr", "ascella", "027 ascella"),
#        ("deCnc", "asellus australis", "028 asellus australis 1/2"),
#        ("gaCnc", "asellus borealis", "029 asellus borealis 2/2"),
#        ("zeCet", "baten kaitos", "030 baten kaitos"),
#        ("gaOri", "bellatrix", "031 bellatrix"),
#        ("alOri", "betelgeuse", "032 betelgeuse"),
#        ("rhCap", "bos", "033 bos"),
#        ("alCen", "bungula", "034 bungula"),
#        ("alCar", "canopus", "035 canopus"),
#        ("alAur", "capella", "036 capella"),
#        ("gaVir", "porrima", "037 porrima, caphir"),
#        ("NGC869", "capulus", "038 capulus"),
#        ("alGem", "castor", "039 castor"),
#        ("epCap", "castra", "040 castra"),
#        ("al-2CVn", "cor caroli", "041 cor caroli, copula"),
#        ("be-1Cap", "dabih", "042 dabih"),
#        ("zeAql", "dheneb", "043 dheneb"),
#        ("alCyg", "deneb", "044 deneb"),
#        ("deCap", "deneb algedi", "045 deneb algedi"),
#        ("beLeo", "denebola", "046 denebola"),
#        ("beCet", "difda", "047 difda"),
#        ("muGem", "tejat", "048 tejat, dirah"),
#        ("thCap", "dorsum", "049 dorsum"),
#        ("beTau", "el nath", "050 el nath"),
#        ("M42", "ensis", "051 orion nebula"),
#        ("M22", "facies", "052 facies"),
#        ("alPsA", "fomalhaut", "053 fomalhaut"),
#        ("etCar", "foramen", "054 foramen"),
#        ("al-1Cap", "giedi prima", "055 giedi prima, algedi"),
#        ("be-1Sco", "graffias", "056 graffias"),
#        ("alAri", "hamal", "057 hamal"),
#        ("zeOph", "han", "058 han"),
#        ("deSco", "dschubba", "059 dschubba, isidis"),
#        ("laVir", "khambalia", "060 khambalia"),
#        ("deCrt", "labrum", "061 labrum"),
#        ("upSco", "lesath", "062 lesath"),
#        ("omiSgr", "manubrium", "063 manubrium"),
#        ("alPeg", "markab", "064 markab"),
#        ("kaVel", "markeb", "065 markeb"),
#        ("beAur", "menkalinan", "066 menkalinan"),
#        ("alCet", "menkar", "067 menkar"),
#        ("deOri", "mintaka", "068 mintaka, cingula orionis 2/2"),
#        ("beAnd", "mirach", "069 mirach"),
#        ("gaCap", "nashira", "070 nashira"),
#        ("piCap", "oculus", "071 oculus"),
#        ("siSgr", "nunki", "072 nunki, pelagus"),
#        ("alCol", "phact", "073 phact"),
#        ("etTau", "alcyone", "074 alcyone, pleiades"),
#        ("alUMi", "polaris", "075 polaris"),
#        ("muSgr", "polis", "076 polis"),
#        ("beGem", "pollux", "077 pollux"),
#        ("M44", "praesepe cluster", "078 praesepe cluster"),
#        ("gaTau", "prima hyadum", "079 prima hyadum"),
#        ("deBoo", "princeps", "080 princeps"),
#        ("alCMi", "procyon", "081 procyon"),
#        ("etGem", "propus", "082 propus"),
#        ("alOph", "rasalhague", "083 rasalhague"),
#        ("beDra", "rastaban", "084 rastaban"),
#        ("alLeo", "regulus", "085 regulus"),
#        ("beOri", "rigel", "086 rigel"),
#        ("etOph", "sabik", "087 sabik"),
#        ("alAqr", "sadalmelik", "088 sadalmelik"),
#        ("beAqr", "sadalsuud", "089 sadalsuud"),
#        ("beLib", "zubeneshamali", "090 zubeneshamali"),
#        ("al-2Lib", "zubenelgenubi", "091 zubenelgenubi"),
#        ("bePeg", "scheat", "092 scheat"),
#        ("gaBoo", "seginus", "093 seginus"),
#        ("beAri", "sheratan", "094 sheratan"),
#        ("nuOph", "sinistra", "095 sinistra"),
#        ("alCMa", "sirius", "096 sirius"),
#        ("deAqr", "skat", "097 skat"),
#        ("alVir", "spica", "098 spica"),
#        ("NGC6530", "spiculum", "099 spiculum, 2 clusters & nebulae"),
#        ("muGem", "tejat", "100 tejat"),
#        ("omeSgr", "terebellium", "101 terebellium"),
#        ("alSer", "unukalhai", "102 unukalhai"),
#        ("M31", "andromeda galaxy", "103 andromeda galaxy, vertex"),
#        ("epVir", "vindemiatrix", "104 vindemiatrix"),
#        ("deGem", "wasat", "105 wasat"),
#        ("alLyr", "vega", "106 vega"),
#        ("deOph", "yed prior", "107 yed prior"),
#        ("etVir", "zaniah", "108 zaniah"),
#        ("beVir", "zavijava", "109 zavijava"),
#        ("deLeo", "zosma", "110 zosma"),
#        ("alHer", "rasalgethi", "111 rasalgethi"),
#        ("zeEri", "zibal", "112 zibal"),
#        ("zeUMa", "mizar", "113 mizar"),
#        ("thLeo", "chort", "114 chort, chertan, cestan, coxa"),
#        ("zeDra", "aldhibah", "115 aldhibah"),
#        ("alTri", "mothallah", "116 mothallah"),
#        ("deHer", "sarin", "117 sarin"),
#    ],
# ---
#    "alphabetical": [  # 521 cleaned
#        ("dePsA", "aboras", ""),
#        ("upCet", "abyssus aqueus", ""),
#        ("th-1Eri", "acamar", ""),
#        ("alEri", "achernar", ""),
#        ("etCas", "achird", ""),
#        ("alCru", "acrux", ""),
#        ("alCnc", "acubens", "ashlesha (colebrook)"),
#        ("M6", "aculeus", ""),
#        ("M7", "acumen", ""),
#        ("epCMa", "adara", "adhara"),
#        ("upAnd", "adhab", "titawin"),
#        ("zeLeo", "adhafera", ""),
#        ("xiAnd", "adhil", ""),
#        ("piPup", "ahadi", ""),
#        ("epTau", "ain", ""),
#        ("gaSer", "ainalhai", ""),
#        ("nu-1Sgr", "ainalrami", "ain al rami"),
#        ("gaOph", "al durajah", ""),
#        ("thUMa", "al haud", ""),
#        ("zeTau", "al hecka", "tianguan"),
#        ("etLeo", "al jabhah", ""),
#        ("ioHer", "al jathiyah", ""),
#        ("rhCep", "al kalb al rai", ""),
#        ("kaGem", "al krikab", ""),
#        ("kaCol", "al kurud", ""),
#        ("siHya", "al minliar al shuja", "minchir"),
#        ("ph-1Cet", "al nitham", ""),
#        ("etPsc", "al pherg", ""),
#        ("taPup", "al rihla", "rehla, anazitisi"),
#        ("piCet", "al sadr al ketus", ""),
#        ("beCnc", "al tarf", ""),
#        ("laAql", "al thalimaim anterior", ""),
#        ("ioAql", "al thalimaim posterior", ""),
#        ("etLyr", "aladfar", ""),
#        ("etCep", "alagemin", ""),
#        ("omeDra", "alathfar", "al athfar (omedra; actually mu lyrae)"),
#        ("muLyr", "alathfar", "al athfar"),
#        ("piSgr", "albaldah", ""),
#        ("epAqr", "albali", "altager"),
#        ("be-1Cyg", "albireo", ""),
#        ("nuAqr", "albulaan", ""),
#        ("alCrv", "alchiba", "alchita"),
#        ("80UMa", "alcor", "(alc0), arundhati, saidak"),
#        ("etTau", "alcyone", "krttika"),
#        ("beCom", "aldafirah", ""),
#        ("alTau", "aldebaran", "rohini"),
#        ("alCep", "alderamin", ""),
#        ("gaGru", "aldhanab", "al dhanab, ras alkurki"),
#        ("etDra", "aldhibain", "athebyne"),
#        ("alCrA", "alfecca meridiana", "alfecca / meridiana"),
#        ("al-1Cap", "algedi", "giedi prima"),
#        ("al-2Cap", "algedi", "giedi secunda"),
#        ("gaPeg", "algenib", "uttarabhadra"),
#        ("ga-1Leo", "algieba", ""),
#        ("bePer", "algol", ""),
#        ("deCrv", "algorab", "hasta"),
#        ("ioCen", "alhakim", ""),
#        ("gaGem", "alhena", "almeisan"),
#        ("zeUMi", "alifa al farkadain", "alifa al / farkadain, pharkadain"),
#        ("epUMa", "alioth", "angiras"),
#        ("etUMa", "alkaid", "benetnash, marichi"),
#        ("mu-1Boo", "alkalurops", ""),
#        ("upPeg", "alkarab", ""),
#        ("alCrt", "alkes", ""),
#        ("thCep", "alkidr", ""),
#        ("ga-1And", "almaak", "almak, almac, almach"),
#        ("kaLeo", "alminhar", "al minliar al asad"),
#        ("alGru", "alnair", ""),
#        ("gaSgr", "alnasl", "(gasgr)"),
#        ("ga-2Sgr", "alnasl", "(ga-2sgr), nash"),
#        ("epOri", "alnilam", "ganesha"),
#        ("zeOri", "alnitak", "iyappa"),
#        ("siSco", "alniyat", ""),
#        ("alHya", "alphard", "cor hydrae"),
#        ("alCrB", "alphecca", "alphekka, gemma"),
#        ("alAnd", "alpheratz", "sirrah"),
#        ("beCep", "alphirk", "alfirk"),
#        ("deCep", "alradif", "alredif"),
#        ("gaCep", "alrai", "errai"),
#        ("alPsc", "alrischa", "alrescha, al rescha"),
#        ("siDra", "alsafi", "athafi"),
#        ("31Lyn", "alsciaukat", "mabsuthat"),
#        ("deVel", "alsephina", "koo she"),
#        ("beAql", "alshain", ""),
#        ("beCrt", "alsharasif", ""),
#        ("nuCap", "alshat", ""),
#        ("laVel", "alsuhail", "suhail"),
#        ("alAql", "altair", "shravana"),
#        ("thCet", "altawk", ""),
#        ("laLeo", "alterf", ""),
#        ("laTau", "althaur", ""),
#        ("etCMa", "aludra", ""),
#        ("xiUMa", "alula australis", ""),
#        ("nuUMa", "alula borealis", ""),
#        ("ioCep", "alvahet", ""),
#        ("alLyn", "alvashak", "al fahd"),
#        ("beDra", "alwaid", "rastaban"),
#        ("th-1Ser", "alya", ""),
#        ("xiGem", "alzirr", ""),
#        ("thAqr", "ancha", ""),
#        ("M31", "andromeda galaxy", ""),
#        ("ta-2Eri", "angetenar", ""),
#        ("alPhe", "ankaa", ""),
#        ("alVul", "anser", ""),
#        ("alSco", "antares", "jyeshtha"),
#        ("taPsc", "anunitum", ""),
#        ("etUMi", "anwar al farkadain", ""),
#        ("Apex", "apex", "(of the sun's way)"),
#        ("alAra", "ara", ""),
#        ("alBoo", "arcturus", "svati"),
#        ("be-2Sgr", "arkab posterior", ""),
#        ("be-1Sgr", "arkab prior", ""),
#        ("etCap", "armus", ""),
#        ("alLep", "arneb", ""),
#        ("muDra", "arrakis", "alrakis"),
#        ("zeSgr", "ascella", ""),
#        ("deCnc", "asellus australis", "pushya"),
#        ("gaCnc", "asellus borealis", ""),
#        ("thBoo", "asellus primus", ""),
#        ("ioBoo", "asellus secundus", ""),
#        ("ka-2Boo", "asellus tertius", ""),
#        ("epHya", "ashlesha", ""),
#        ("beCVn", "asterion", "chara"),
#        ("21Tau", "asterope", "sterope i"),
#        ("omiPer", "atik", "atiks"),
#        ("omiTau", "atirsagne", ""),
#        ("27Tau", "atlas", ""),
#        ("alTrA", "atria", ""),
#        ("deVir", "auva", "mineluva"),
#        ("epCar", "avior", ""),
#        ("etCrv", "avis satyra", ""),
#        ("pi-1Cyg", "azelfafage", ""),
#        ("etEri", "azha", ""),
#        ("xiPup", "azmidiske", ""),
#        ("v2500 oph", "barnard's star", ""),
#        ("omeCap", "baten algiedi", ""),
#        ("zeCet", "baten kaitos", ""),
#        ("phDra", "batentaban australis", ""),
#        ("chDra", "batentaban borealis", ""),
#        ("etAql", "bazak", ""),
#        ("up-3Eri", "beemim", ""),
#        ("omi-1Eri", "beid", ""),
#        ("gaOri", "bellatrix", "durga"),
#        ("12Aql", "bered", ""),
#        ("alOri", "betelgeuse", "beteigeuse, ardra"),
#        ("41Ari", "bharani", ""),
#        ("thPeg", "biham", "baham"),
#        ("epCen", "birdun", ""),
#        ("thAur", "bogardus", "manus, mahasim"),
#        ("rhCap", "bos", ""),
#        ("deAri", "botein", ""),
#        ("siLib", "brachium", ""),
#        ("xiAqr", "bunda", ""),
#        ("alCar", "canopus", "agastya"),
#        ("alAur", "capella", "brahmahridaya"),
#        ("beCas", "caph", ""),
#        ("NGC869", "capulus", ""),
#        ("alGem", "castor", ""),
#        ("epCap", "castra", ""),
#        ("up-2Cas", "castula", ""),
#        ("gaHya", "cauda hydrae", "dhanab al shuja"),
#        ("phBoo", "ceginus", ""),
#        ("16Tau", "celaeno", ""),
#        ("beOph", "celbalrai", "cebalrai, kelb alrai"),
#        ("muAra", "cervantes", ""),
#        ("47UMa", "chalawan", ""),
#        ("beSer", "chow", "zhou"),
#        ("55Cnc", "copernicus", ""),
#        ("al-2CVn", "cor caroli", ""),
#        ("thLeo", "coxa", "chertan, cestan, chort"),
#        ("beEri", "cursa", ""),
#        ("be-1Cap", "dabih", ""),
#        ("ioCnc", "decapoda", ""),
#        ("deCru", "decrux", ""),
#        ("deAql", "delta aquilae", "al mizan"),
#        ("alCyg", "deneb", ""),
#        ("deCap", "deneb algedi", ""),
#        ("etCet", "deneb algenubi", ""),
#        ("epDel", "deneb dulphim", "aldulfin"),
#        ("zeAql", "deneb el okab australis", "dheneb"),
#        ("epAql", "deneb el okab borealis", ""),
#        ("ioCet", "deneb kaitos", "shemali"),
#        ("beLeo", "denebola", "uttaraphalguni"),
#        ("alCom", "diadem", ""),
#        ("beCet", "diphda", "difda"),
#        ("thCap", "dorsum", ""),
#        ("chCar", "drus", "drys"),
#        ("deSco", "dschubba", "anuradha"),
#        ("alUMa", "dubhe", "kratu"),
#        ("ps-1Dra", "dziban", ""),
#        ("ioDra", "edasich", "ed asich"),
#        ("laAqr", "ekkhysis", "hydor, shatabhishaj, shatabhishak"),
#        ("chUMa", "el kophrah", "taiyangshou"),
#        ("17Tau", "electra", ""),
#        ("beTau", "elnath", "el nath, alnath"),
#        ("gaDra", "eltanin", "etamin"),
#        ("epPeg", "enif", ""),
#        ("etOri", "ensis", ""),
#        ("muCep", "erakis", "the garnet star"),
#        ("M22", "facies", ""),
#        ("32Dra", "fafnir", "32dra"),
#        ("42Dra", "fafnir", "42dra"),
#        ("piSco", "fang", ""),
#        ("alPsA", "fomalhaut", ""),
#        ("etCar", "foramen", ""),
#        ("alFor", "fornacis", "dalim"),
#        ("piHer", "fudail", ""),
#        ("zeCas", "fulu", ""),
#        ("bePsc", "fum alsamakah", "samakah"),
#        ("nuTau", "furibundus", ""),
#        ("zeCMa", "furud", ""),
#        ("HR6630", "fuyue", ""),
#        ("gaCru", "gacrux", ""),
#        ("GEqu", "galequ", "galactic equator (only exact for year 2000)"),
#        ("GPPlan", "galplane pole", "galactic plane pole (true gal plane by dk)"),
#        ("GPol", "galpole", "galactic pole (liu/zhu/zhang)"),
#        ("GP1958", "galpole iau1958", "galactic pole (old) (iau1958)"),
#        ("SgrA*", "galactic center", "(old)"),
#        ("GCLiu", "gcliu", "galactic center (new) (liu/zhu/zhang 2010)"),
#        ("deCol", "ghusn al zaitun", ""),
#        ("laDra", "giansar", "giausar, gianfar"),
#        ("gaCrv", "gienah", "gienah corvi"),
#        ("epCyg", "gienah cygni", "ghurab, aljanah"),
#        ("kaSco", "girtab", ""),
#        ("beCMi", "gomeisa", ""),
#        ("omePer", "gorgona quatra", ""),
#        ("piPer", "gorgona secunda", ""),
#        ("rhPer", "gorgona tertia", ""),
#        ("be-1Sco", "graffias", "akrab, acrab"),
#        ("xiSco", "grafias", ""),
#        ("GA", "great attractor", ""),
#        ("beGru", "gruid", "tiaki"),
#        ("xiDra", "grumium", ""),
#        ("beCen", "hadar", "agena"),
#        ("zeAur", "haedi", "hoedus i, sadatoni, saclateni"),
#        ("alAri", "hamal", ""),
#        ("zeOph", "han", ""),
#        ("ioAur", "hasseleh", "hassaleh, al khabdhilinan"),
#        ("ioOri", "hatsya", "nair al saif"),
#        ("taSgr", "hecatebolus", ""),
#        ("kaOph", "helkath", ""),
#        ("51Peg", "helvetios", ""),
#        ("rhBoo", "hemelein prima", "al hamalain"),
#        ("siBoo", "hemelein secunda", ""),
#        ("zeVir", "heze", ""),
#        ("deLup", "hilasmus", ""),
#        ("etAur", "hoedus ii", "haedus"),
#        ("zePeg", "homam", ""),
#        ("gaTau", "hyadum i", "prima hyadum"),
#        ("de-1Tau", "hyadum ii", "secunda hyadum (de-1tau)"),
#        ("etAqr", "hydria", "deli"),
#        ("zeHya", "hydrobius", ""),
#        ("rhSco", "iklil", ""),
#        ("thOph", "imad", ""),
#        ("IDrag", "infrared dragon", "(doomsday key)"),
#        ("HR3743", "intercrus", ""),
#        ("epBoo", "izar", "mirak, pulcherrima"),
#        ("nuSco", "jabbah", ""),
#        ("ome-1Sco", "jabhat al akrab", "(ome-1sco)"),
#        ("ome-2Sco", "jabhat al akrab", "(ome-2sco)"),
#        ("kaPeg", "jih", ""),
#        ("omiGem", "jishui", ""),
#        ("epCru", "juxta crucem", "ginan"),
#        ("nuCen", "kabkent secunda", ""),
#        ("phCen", "kabkent tertia", ""),
#        ("gaCet", "kaffaljidhma", ""),
#        ("epPsc", "kaht", ""),
#        ("nuPup", "kaimana", ""),
#        ("epHer", "kajam epsher", "kajam (epsher)"),
#        ("omeHer", "kajam omeher", "kajam (omeher), cujam"),
#        ("alLup", "kakkab", "men"),
#        ("kaVir", "kang", ""),
#        ("muTau", "kattupothu", ""),
#        ("epSgr", "kaus australis", ""),
#        ("laSgr", "kaus borealis", ""),
#        ("deSgr", "kaus media", "meridionalis, purvashadha"),
#        ("kaCen", "ke kwan", ""),
#        ("laGem", "kebash", "alkibash"),
#        ("omi-2Eri", "keid", ""),
#        ("beLup", "kekouan", ""),
#        ("taPeg", "kerb", "salm"),
#        ("kaDra", "ketu", ""),
#        ("laVir", "khambalia", ""),
#        ("gaCom", "kissin", ""),
#        ("alEqu", "kitalpha", ""),
#        ("beUMi", "kochab", ""),
#        ("beHer", "kornephoros", ""),
#        ("beCrv", "kraz", ""),
#        ("nu-1Dra", "kuma", "(nu-1dra)"),
#        ("nu-2Dra", "kuma", "(nu-2dra)"),
#        ("xiCep", "kurdah", "alkurhah"),
#        ("zeCep", "kurhah", ""),
#        ("deCrt", "labrum", ""),
#        ("muSer", "leiolepis", "leiolepidotus"),
#        ("upSco", "lesath", ""),
#        ("xiAqr", "libertas", ""),
#        ("39Ari", "lilii borea", ""),
#        ("dePsc", "linteum", ""),
#        ("laCen", "ma ti", "mati"),
#        ("epAur", "maaz", "almaaz, al anz"),
#        ("kaLyn", "mabsuthat", ""),
#        ("38Lyn", "maculosa", "maculata"),
#        ("20Tau", "maia", ""),
#        ("omiSgr", "manubrium", ""),
#        ("zeCap", "marakk", ""),
#        ("muCas", "marfak", ""),
#        ("laOph", "marfik", ""),
#        ("alPeg", "markab", "purvabhadra"),
#        ("kaVel", "markeb", ""),
#        ("kaHer", "marsik", "marsic, marfik"),
#        ("laHer", "masym", "maasym"),
#        ("etPeg", "matar", ""),
#        ("deHya", "mautinah", ""),
#        ("epGem", "mebsuta", ""),
#        ("deUMa", "megrez", "atri"),
#        ("laOri", "meissa", "heka, mrgashirsha, mrigashirsha"),
#        ("zeGem", "mekbuda", ""),
#        ("epCnc", "meleph", ""),
#        ("muHer", "melkarth", ""),
#        ("beAur", "menkalinan", ""),
#        ("alCet", "menkar", ""),
#        ("laCet", "menkar", ""),
#        ("thCen", "menkent", ""),
#        ("xiPer", "menkib", ""),
#        ("beUMa", "merak", "pulaha"),
#        ("38Boo", "merga", ""),
#        ("23Tau", "merope", ""),
#        ("gaAri", "mesarthim", ""),
#        ("M49", "messier 49", ""),
#        ("M87", "messier 87", ""),
#        ("beCar", "miaplacidus", ""),
#        ("beCru", "mimosa", ""),
#        ("epCrv", "minkar", ""),
#        ("deOri", "mintaka", "kumara"),
#        ("omiCet", "mira", ""),
#        ("beAnd", "mirach", ""),
#        ("etPer", "miram", ""),
#        ("alPer", "mirfak", "mirphak"),
#        ("beCMa", "mirzam", "murzim, murzims"),
#        ("kaPer", "misam", ""),
#        ("zeUMa", "mizar", "(miz0), vasishtha"),
#        ("etBoo", "mufrid", "muphrid"),
#        ("gaCen", "muhlifain", ""),
#        ("gaCMa", "muliphein", "isis"),
#        ("omiUMa", "muscida", ""),
#        ("18Del", "musica", ""),
#        ("thGem", "nageba", ""),
#        ("phSgr", "nanto", ""),
#        ("zePup", "naos", "suhail hadar"),
#        ("gaCap", "nashira", ""),
#        ("xiSer", "nehushtan", ""),
#        ("beBoo", "nekkar", ""),
#        ("51And", "nembus", ""),
#        ("beLep", "nihal", ""),
#        ("zeDra", "nodus i", "aldhibah"),
#        ("deDra", "nodus ii", "altais"),
#        ("epSer", "nulla pambu", ""),
#        ("siSgr", "nunki", "uttarashadha"),
#        ("beCrB", "nusakan", ""),
#        ("piCap", "oculus", ""),
#        ("HD149026", "ogma", ""),
#        ("M42", "orion nebula", "messier 42"),
#        ("psCap", "pazan", "pazhan"),
#        ("alPav", "peacock", ""),
#        ("muVel", "peregrini", "alherem"),
#        ("alCol", "phact", ""),
#        ("th-1Tau", "phaeo", ""),
#        ("th-2Tau", "phaesula", "chamukuy"),
#        ("gaUMa", "phecda", "pulastya"),
#        ("gaUMi", "pherkad", ""),
#        ("11UMi", "pherkad minor", ""),
#        ("epCep", "phicares", "phicareus"),
#        ("deCet", "phycochroma", ""),
#        ("mu-2Sco", "pipirima", ""),
#        ("28Tau", "pleione", ""),
#        ("nuHya", "pleura", ""),
#        ("alUMi", "polaris", ""),
#        ("siOct", "polaris australis", ""),
#        ("muSgr", "polis", ""),
#        ("beGem", "pollux", "punarvasu"),
#        ("gaVir", "porrima", ""),
#        ("46LMi", "praecipua", ""),
#        ("M44", "praesepe cluster", ""),
#        ("deAur", "prijipati", ""),
#        ("deBoo", "princeps", ""),
#        ("alCMi", "procyon", ""),
#        ("etGem", "propus", "(etagem)"),
#        ("ioGem", "propus iotgem", "propus (iotgem)"),
#        ("V645 Cen", "proxima centauri", ""),
#        ("deSer", "qin", "chin"),
#        ("epEri", "ran", ""),
#        ("deEri", "rana", ""),
#        ("muVir", "ril alauva", "rijl al awwa, ras alauva"),
#        ("alHer", "rasalgethi", ""),
#        ("alOph", "rasalhague", ""),
#        ("alLeo", "regulus", "magha"),
#        ("zePsc", "revati", "(zepsc)"),
#        ("beOri", "rigel", ""),
#        (
#            "alCen",
#            "rigil kentaurus",
#            "rigel kentaurus, toliman, bungula, proxima centauri",
#        ),
#        ("muVir", "rijl al awwa", "ril alauva"),
#        ("deBoo", "rotanev", "dhanishtha, shravishtha"),
#        ("deCyg", "ruc", "rukh, urakhga, al fawaris"),
#        ("deCas", "ruchbah", "rucha"),
#        ("ome-1Cyg", "ruchbah i", ""),
#        ("ome-2Cyg", "ruchbah ii", ""),
#        ("thHer", "rukbalgethi genubi", ""),
#        ("taHer", "rukbalgethi shemali", ""),
#        ("alSgr", "rukbat", ""),
#        ("zeHer", "rutilicus", ""),
#        ("etOph", "sabik", ""),
#        ("gaAqr", "sadalachbia", "sadachbia"),
#        ("laPeg", "sadalbari", ""),
#        ("alAqr", "sadalmelek", "sadalmelik"),
#        ("beAqr", "sadalsuud", ""),
#        ("ze-1Aqr", "sadaltager", ""),
#        ("gaCyg", "sador", "sadir, sadr"),
#        ("kaOri", "saiph", ""),
#        ("SN1987A", "sanduleak", ""),
#        ("thSco", "sargas", ""),
#        ("deHer", "sarin", ""),
#        ("epLep", "sasin", ""),
#        ("piHya", "sataghni", ""),
#        ("53Eri", "sceptrum", ""),
#        ("bePeg", "scheat", ""),
#        ("alCas", "schedar", "shedir, schedir"),
#        ("ioCar", "scutulum", "tureis, aspidiske"),
#        ("piAqr", "seat", ""),
#        ("deTau", "secunda hyadum", "(detau)"),
#        ("epCas", "segin", ""),
#        ("gaBoo", "seginus", "haris"),
#        ("etSgr", "sephdar", "ira furoris"),
#        ("alSge", "sham", ""),
#        ("ACO3558", "shapley supercluster", "a3558"),
#        ("laSco", "shaula", "mula"),
#        ("beLyr", "sheliak", ""),
#        ("beAri", "sheratan", "ashvini"),
#        ("rhLeo", "shir", ""),
#        ("siLeo", "shishimai", ""),
#        ("omeCar", "simiram", ""),
#        ("gaPsc", "simmah", ""),
#        ("nuOph", "sinistra", ""),
#        ("alCMa", "sirius", "lubdhaka"),
#        ("kaAqr", "situla", ""),
#        ("deAqr", "skat", ""),
#        ("etHer", "sofian", ""),
#        ("alVir", "spica", "citra"),
#        ("NGC6530", "spiculum", ""),
#        ("22Tau", "sterope ii", ""),
#        ("alDel", "sualocin", ""),
#        ("omiLeo", "subra", ""),
#        ("ga-2Vel", "suhail al muhlif", "regor"),
#        ("gaLyr", "sulaphat", "sulafat"),
#        ("ioVir", "syrma", ""),
#        ("pi-3Ori", "tabit", "(pi-3ori)"),
#        ("pi-4Ori", "tabit", "(pi-4ori)"),
#        ("8Dra", "taiyi", ""),
#        ("ioUMa", "talitha", "borealis"),
#        ("kaUMa", "talitha australis", "alkaphrah"),
#        ("etSer", "tang", ""),
#        ("muUMa", "tania australis", ""),
#        ("laUMa", "tania borealis", ""),
#        ("gaAql", "tarazed", ""),
#        ("19Tau", "taygeta", ""),
#        ("zeCnc", "tegmen", "tegmine"),
#        ("muGem", "tejat", ""),
#        ("omeSgr", "terebellium", ""),
#        ("upOri", "thabit", ""),
#        ("taCrB", "blaze star", ""),
#        ("up-2Eri", "theemin", ""),
#        ("alDra", "thuban", "dhruva"),
#        ("gaLup", "thusia", ""),
#        ("7Dra", "tianyi", ""),
#        ("bePsA", "tien kang", ""),
#        ("HR4609", "tonatiuh", ""),
#        (
#            "omiPsc",
#            "torcularis septentrionalis",
#            "torcular",
#        ),
#        ("th-1Ori", "trapezium", ""),
#        ("trappist-1", "trappist-1", ""),
#        ("ioLeo", "tse tseng", "tsze tseang"),
#        ("thAql", "tseen foo", ""),
#        ("phVel", "tseen ke", ""),
#        ("gaCas", "tsih", "cih"),
#        ("laCol", "tsze", ""),
#        ("rhPup", "turais", "tureis"),
#        ("epDra", "tyl", ""),
#        ("ta-1Hya", "ukdah", "prima"),
#        ("ta-2Hya", "ukdah secunda", "secunda"),
#        ("alSer", "unukalhai", "cor serpentis"),
#        ("siCMa", "unurgunite", ""),
#        ("epUMi", "urodelus", ""),
#        ("xiTau", "ushakaron", ""),
#        ("thCar", "vathorz posterior", ""),
#        ("upCar", "vathorz prior", ""),
#        ("alLyr", "vega", "abhijit"),
#        ("14And", "veritate", ""),
#        ("omePsc", "vernalis", ""),
#        ("epVir", "vindemiatrix", ""),
#        ("VC", "virgo cluster", ""),
#        ("io-1Lib", "vishakha", ""),
#        ("deGem", "wasat", ""),
#        ("beCol", "wazn", ""),
#        ("epSco", "wei", "larawag"),
#        ("deCMa", "wezen", ""),
#        ("zePhe", "wurren", ""),
#        ("mu-1Sco", "xamidimura", ""),
#        ("omiVel", "xestus", ""),
#        ("laBoo", "xuange", ""),
#        ("epOph", "yed posterior", ""),
#        ("deOph", "yed prior", ""),
#        ("deUMi", "yildun", ""),
#        ("etVir", "zaniah", ""),
#        ("gaEri", "zaurak", ""),
#        ("beVir", "zavijava", "alaraph"),
#        ("up-1Hya", "zhang", ""),
#        ("zeEri", "zibal", ""),
#        ("deLeo", "zosma", "dhur, purvaphalguni"),
#        ("gaLib", "zubenelakrab", "zubenelhakrabi, zuben elakrab"),
#        ("deLib", "zubenelakribi", "zuben elakribi"),
#        ("al-2Lib", "zubenelgenubi", "zuben elgenubi"),
#        ("beLib", "zubeneshamali", "zuben eschamali"),
#        ("nuLib", "zubenhakrabi", "zuben hakrabi"),
#    ],
# ---
#    "alphabetical": [  # 521
#        ("dePsA", "aboras", "aboras"),
#        ("upCet", "abyssus aqueus", "abyssus aqueus"),
#        ("th-1Eri", "acamar", "acamar"),
#        ("alEri", "achernar", "achernar"),
#        ("etCas", "achird", "achird"),
#        ("alCru", "acrux", "acrux"),
#        ("alCnc", "acubens", "acubens, ashlesha (colebrook)"),
#        ("M6", "aculeus", "aculeus"),
#        ("M7", "acumen", "acumen"),
#        ("epCMa", "adara", "adara, adhara"),
#        ("upAnd", "adhab", "adhab, titawin"),
#        ("zeLeo", "adhafera", "adhafera"),
#        ("xiAnd", "adhil", "adhil"),
#        ("piPup", "ahadi", "ahadi"),
#        ("epTau", "ain", "ain"),
#        ("gaSer", "ainalhai", "ainalhai"),
#        ("nu-1Sgr", "ainalrami", "ainalrami, ain al rami"),
#        ("gaOph", "al durajah", "al durajah"),
#        ("thUMa", "al haud", "al haud"),
#        ("zeTau", "al hecka", "al hecka, tianguan"),
#        ("etLeo", "al jabhah", "al jabhah"),
#        ("ioHer", "al jathiyah", "al jathiyah"),
#        ("rhCep", "al kalb al rai", "al kalb al rai"),
#        ("kaGem", "al krikab", "al krikab"),
#        ("kaCol", "al kurud", "al kurud"),
#        ("siHya", "al minliar al shuja", "al minliar al shuja, minchir"),
#        ("ph-1Cet", "al nitham", "al nitham"),
#        ("etPsc", "al pherg", "al pherg"),
#        ("taPup", "al rihla", "al rihla, rehla, anazitisi"),
#        ("piCet", "al sadr al ketus", "al sadr al ketus"),
#        ("beCnc", "al tarf", "al tarf"),
#        ("laAql", "al thalimaim anterior", "al thalimaim anterior"),
#        ("ioAql", "al thalimaim posterior", "al thalimaim posterior"),
#        ("etLyr", "aladfar", "aladfar"),
#        ("etCep", "alagemin", "alagemin"),
#        ("omeDra", "alathfar", "alathfar / al athfar (omedra; actually mu lyrae)"),
#        ("muLyr", "alathfar", "alathfar, al athfar"),
#        ("piSgr", "albaldah", "albaldah"),
#        ("epAqr", "albali", "albali, altager"),
#        ("be-1Cyg", "albireo", "albireo"),
#        ("nuAqr", "albulaan", "albulaan"),
#        ("alCrv", "alchiba", "alchiba, alchita"),
#        ("80UMa", "alcor", "alcor (alc0), arundhati, saidak"),
#        ("etTau", "alcyone", "alcyone, krttika"),
#        ("beCom", "aldafirah", "aldafirah"),
#        ("alTau", "aldebaran", "aldebaran, rohini"),
#        ("alCep", "alderamin", "alderamin"),
#        ("gaGru", "aldhanab", "aldhanab, al dhanab, ras alkurki"),
#        ("etDra", "aldhibain", "aldhibain, athebyne"),
#        ("alCrA", "alfecca meridiana", "alfecca / meridiana"),
#        ("al-1Cap", "algedi", "algedi, giedi prima"),
#        ("al-2Cap", "algedi", "algedi, giedi secunda"),
#        ("gaPeg", "algenib", "algenib, uttarabhadra"),
#        ("ga-1Leo", "algieba", "algieba"),
#        ("bePer", "algol", "algol"),
#        ("deCrv", "algorab", "algorab, hasta"),
#        ("ioCen", "alhakim", "alhakim"),
#        ("gaGem", "alhena", "alhena, almeisan"),
#        ("zeUMi", "alifa al farkadain", "alifa al / farkadain, pharkadain"),
#        ("epUMa", "alioth", "alioth, angiras"),
#        ("etUMa", "alkaid", "alkaid, benetnash, marichi"),
#        ("mu-1Boo", "alkalurops", "alkalurops"),
#        ("upPeg", "alkarab", "alkarab"),
#        ("alCrt", "alkes", "alkes"),
#        ("thCep", "alkidr", "alkidr"),
#        ("ga-1And", "almaak", "almaak, almak, almac, almach"),
#        ("kaLeo", "alminhar", "alminhar, al minliar al asad"),
#        ("alGru", "alnair", "alnair"),
#        ("gaSgr", "alnasl", "alnasl (gasgr)"),
#        ("ga-2Sgr", "alnasl", "alnasl (ga-2sgr), nash"),
#        ("epOri", "alnilam", "alnilam, ganesha"),
#        ("zeOri", "alnitak", "alnitak, iyappa"),
#        ("siSco", "alniyat", "alniyat"),
#        ("alHya", "alphard", "alphard, cor hydrae"),
#        ("alCrB", "alphecca", "alphecca, alphekka, gemma"),
#        ("alAnd", "alpheratz", "alpheratz, sirrah"),
#        ("beCep", "alphirk", "alphirk, alfirk"),
#        ("deCep", "alradif", "alradif, alredif"),
#        ("gaCep", "alrai", "alrai, errai"),
#        ("alPsc", "alrischa", "alrischa, alrescha, al rescha"),
#        ("siDra", "alsafi", "alsafi, athafi"),
#        ("31Lyn", "alsciaukat", "alsciaukat, mabsuthat"),
#        ("deVel", "alsephina", "alsephina, koo she"),
#        ("beAql", "alshain", "alshain"),
#        ("beCrt", "alsharasif", "alsharasif"),
#        ("nuCap", "alshat", "alshat"),
#        ("laVel", "alsuhail", "alsuhail, suhail"),
#        ("alAql", "altair", "altair, shravana"),
#        ("thCet", "altawk", "altawk"),
#        ("laLeo", "alterf", "alterf"),
#        ("laTau", "althaur", "althaur"),
#        ("etCMa", "aludra", "aludra"),
#        ("xiUMa", "alula australis", "alula australis"),
#        ("nuUMa", "alula borealis", "alula borealis"),
#        ("ioCep", "alvahet", "alvahet"),
#        ("alLyn", "alvashak", "alvashak, al fahd"),
#        ("beDra", "alwaid", "alwaid, rastaban"),
#        ("th-1Ser", "alya", "alya"),
#        ("xiGem", "alzirr", "alzirr"),
#        ("thAqr", "ancha", "ancha"),
#        ("M31", "andromeda galaxy", "andromeda galaxy"),
#        ("ta-2Eri", "angetenar", "angetenar"),
#        ("alPhe", "ankaa", "ankaa"),
#        ("alVul", "anser", "anser"),
#        ("alSco", "antares", "antares, jyeshtha"),
#        ("taPsc", "anunitum", "anunitum"),
#        ("etUMi", "anwar al farkadain", "anwar al farkadain"),
#        ("Apex", "apex", "apex (of the sun's way)"),
#        ("alAra", "ara", "ara"),
#        ("alBoo", "arcturus", "arcturus, svati"),
#        ("be-2Sgr", "arkab posterior", "arkab posterior"),
#        ("be-1Sgr", "arkab prior", "arkab prior"),
#        ("etCap", "armus", "armus"),
#        ("alLep", "arneb", "arneb"),
#        ("muDra", "arrakis", "arrakis, alrakis"),
#        ("zeSgr", "ascella", "ascella"),
#        ("deCnc", "asellus australis", "asellus australis, pushya"),
#        ("gaCnc", "asellus borealis", "asellus borealis"),
#        ("thBoo", "asellus primus", "asellus primus"),
#        ("ioBoo", "asellus secundus", "asellus secundus"),
#        ("ka-2Boo", "asellus tertius", "asellus tertius"),
#        ("epHya", "ashlesha", "ashlesha"),
#        ("beCVn", "asterion", "asterion, chara"),
#        ("21Tau", "asterope", "sterope i, asterope"),
#        ("omiPer", "atik", "atik, atiks"),
#        ("omiTau", "atirsagne", "atirsagne"),
#        ("27Tau", "atlas", "atlas"),
#        ("alTrA", "atria", "atria"),
#        ("deVir", "auva", "auva, mineluva"),
#        ("epCar", "avior", "avior"),
#        ("etCrv", "avis satyra", "avis satyra"),
#        ("pi-1Cyg", "azelfafage", "azelfafage"),
#        ("etEri", "azha", "azha"),
#        ("xiPup", "azmidiske", "azmidiske"),
#        ("v2500 oph", "barnard's star", "barnard's star"),
#        ("omeCap", "baten algiedi", "baten algiedi"),
#        ("zeCet", "baten kaitos", "baten kaitos"),
#        ("phDra", "batentaban australis", "batentaban australis"),
#        ("chDra", "batentaban borealis", "batentaban borealis"),
#        ("etAql", "bazak", "bazak"),
#        ("up-3Eri", "beemim", "beemim"),
#        ("omi-1Eri", "beid", "beid"),
#        ("gaOri", "bellatrix", "bellatrix, durga"),
#        ("12Aql", "bered", "bered"),
#        ("alOri", "betelgeuse", "betelgeuse, beteigeuse, ardra"),
#        ("41Ari", "bharani", "bharani"),
#        ("thPeg", "biham", "biham, baham"),
#        ("epCen", "birdun", "birdun"),
#        ("thAur", "bogardus", "bogardus, manus, mahasim"),
#        ("rhCap", "bos", "bos"),
#        ("deAri", "botein", "botein"),
#        ("siLib", "brachium", "brachium"),
#        ("xiAqr", "bunda", "bunda"),
#        ("alCar", "canopus", "canopus, agastya"),
#        ("alAur", "capella", "capella, brahmahridaya"),
#        ("beCas", "caph", "caph"),
#        ("NGC869", "capulus", "capulus"),
#        ("alGem", "castor", "castor"),
#        ("epCap", "castra", "castra"),
#        ("up-2Cas", "castula", "castula"),
#        ("gaHya", "cauda hydrae", "cauda hydrae, dhanab al shuja"),
#        ("phBoo", "ceginus", "ceginus"),
#        ("16Tau", "celaeno", "celaeno"),
#        ("beOph", "celbalrai", "celbalrai, cebalrai, kelb alrai"),
#        ("muAra", "cervantes", "cervantes"),
#        ("47UMa", "chalawan", "chalawan"),
#        ("beSer", "chow", "chow, zhou"),
#        ("55Cnc", "copernicus", "copernicus"),
#        ("al-2CVn", "cor caroli", "cor caroli"),
#        ("thLeo", "coxa", "coxa, chertan, cestan, chort"),
#        ("beEri", "cursa", "cursa"),
#        ("be-1Cap", "dabih", "dabih"),
#        ("ioCnc", "decapoda", "decapoda"),
#        ("deCru", "decrux", "decrux"),
#        ("deAql", "delta aquilae", "delta aquilae, al mizan"),
#        ("alCyg", "deneb", "deneb"),
#        ("deCap", "deneb algedi", "deneb algedi"),
#        ("etCet", "deneb algenubi", "deneb algenubi"),
#        ("epDel", "deneb dulphim", "deneb dulphim, aldulfin"),
#        ("zeAql", "deneb el okab australis", "deneb el okab australis, dheneb"),
#        ("epAql", "deneb el okab borealis", "deneb el okab borealis"),
#        ("ioCet", "deneb kaitos", "deneb kaitos, shemali"),
#        ("beLeo", "denebola", "denebola, uttaraphalguni"),
#        ("alCom", "diadem", "diadem"),
#        ("beCet", "diphda", "diphda, difda"),
#        ("thCap", "dorsum", "dorsum"),
#        ("chCar", "drus", "drus, drys"),
#        ("deSco", "dschubba", "dschubba, anuradha"),
#        ("alUMa", "dubhe", "dubhe, kratu"),
#        ("ps-1Dra", "dziban", "dziban"),
#        ("ioDra", "edasich", "edasich, ed asich"),
#        ("laAqr", "ekkhysis", "ekkhysis, hydor, shatabhishaj, shatabhishak"),
#        ("chUMa", "el kophrah", "el kophrah, taiyangshou"),
#        ("17Tau", "electra", "electra"),
#        ("beTau", "elnath", "elnath, el nath, alnath"),
#        ("gaDra", "eltanin", "eltanin, etamin"),
#        ("epPeg", "enif", "enif"),
#        ("etOri", "ensis", "ensis"),
#        ("muCep", "erakis", "erakis, the garnet star"),
#        ("M22", "facies", "facies"),
#        ("32Dra", "fafnir", "fafnir 32dra"),
#        ("42Dra", "fafnir", "fafnir 42dra"),
#        ("piSco", "fang", "fang"),
#        ("alPsA", "fomalhaut", "fomalhaut"),
#        ("etCar", "foramen", "foramen"),
#        ("alFor", "fornacis", "fornacis, dalim"),
#        ("piHer", "fudail", "fudail"),
#        ("zeCas", "fulu", "fulu"),
#        ("bePsc", "fum alsamakah", "fum alsamakah, samakah"),
#        ("nuTau", "furibundus", "furibundus"),
#        ("zeCMa", "furud", "furud"),
#        ("HR6630", "fuyue", "fuyue"),
#        ("gaCru", "gacrux", "gacrux"),
#        ("GEqu", "galequ", "galactic equator (only exact for year 2000)"),
#        ("GPPlan", "galplane pole", "galactic plane pole (true gal plane by dk)"),
#        ("GPol", "galpole", "galactic pole (liu/zhu/zhang)"),
#        ("GP1958", "galpole iau1958", "galactic pole (old) (iau1958)"),
#        ("SgrA*", "galactic center", "galactic center (old)"),
#        ("GCLiu", "gcliu", "galactic center (new) (liu/zhu/zhang 2010)"),
#        ("deCol", "ghusn al zaitun", "ghusn al zaitun"),
#        ("laDra", "giansar", "giansar, giausar, gianfar"),
#        ("gaCrv", "gienah", "gienah, gienah corvi"),
#        ("epCyg", "gienah cygni", "gienah cygni / ghurab, aljanah"),
#        ("kaSco", "girtab", "girtab"),
#        ("beCMi", "gomeisa", "gomeisa"),
#        ("omePer", "gorgona quatra", "gorgona quatra"),
#        ("piPer", "gorgona secunda", "gorgona secunda"),
#        ("rhPer", "gorgona tertia", "gorgona tertia"),
#        ("be-1Sco", "graffias", "graffias, akrab, acrab"),
#        ("xiSco", "grafias", "grafias"),
#        ("GA", "great attractor", "great attractor"),
#        ("beGru", "gruid", "gruid, tiaki"),
#        ("xiDra", "grumium", "grumium"),
#        ("beCen", "hadar", "hadar, agena"),
#        ("zeAur", "haedi", "hoedus i, haedi, sadatoni, saclateni"),
#        ("alAri", "hamal", "hamal"),
#        ("zeOph", "han", "han"),
#        ("ioAur", "hasseleh", "hasseleh, hassaleh, al khabdhilinan"),
#        ("ioOri", "hatsya", "hatsya, nair al saif"),
#        ("taSgr", "hecatebolus", "hecatebolus"),
#        ("kaOph", "helkath", "helkath"),
#        ("51Peg", "helvetios", "helvetios"),
#        ("rhBoo", "hemelein prima", "hemelein prima, al hamalain"),
#        ("siBoo", "hemelein secunda", "hemelein secunda"),
#        ("zeVir", "heze", "heze"),
#        ("deLup", "hilasmus", "hilasmus"),
#        ("etAur", "hoedus ii", "hoedus ii, haedus"),
#        ("zePeg", "homam", "homam"),
#        ("gaTau", "hyadum i", "hyadum i, prima hyadum"),
#        ("de-1Tau", "hyadum ii", "hyadum ii, secunda hyadum (de-1tau)"),
#        ("etAqr", "hydria", "hydria, deli"),
#        ("zeHya", "hydrobius", "hydrobius"),
#        ("rhSco", "iklil", "iklil"),
#        ("thOph", "imad", "imad"),
#        ("IDrag", "infrared dragon", "infrared dragon (doomsday key)"),
#        ("HR3743", "intercrus", "intercrus"),
#        ("epBoo", "izar", "izar, mirak, pulcherrima"),
#        ("nuSco", "jabbah", "jabbah"),
#        ("ome-1Sco", "jabhat al akrab", "jabhat al akrab (ome-1sco)"),
#        ("ome-2Sco", "jabhat al akrab", "jabhat al akrab (ome-2sco)"),
#        ("kaPeg", "jih", "jih"),
#        ("omiGem", "jishui", "jishui"),
#        ("epCru", "juxta crucem", "juxta crucem, ginan"),
#        ("nuCen", "kabkent secunda", "kabkent secunda"),
#        ("phCen", "kabkent tertia", "kabkent tertia"),
#        ("gaCet", "kaffaljidhma", "kaffaljidhma"),
#        ("epPsc", "kaht", "kaht"),
#        ("nuPup", "kaimana", "kaimana"),
#        ("epHer", "kajam epsher", "kajam (epsher)"),
#        ("omeHer", "kajam omeher", "kajam (omeher), cujam"),
#        ("alLup", "kakkab", "kakkab, men"),
#        ("kaVir", "kang", "kang"),
#        ("muTau", "kattupothu", "kattupothu"),
#        ("epSgr", "kaus australis", "kaus australis"),
#        ("laSgr", "kaus borealis", "kaus borealis"),
#        ("deSgr", "kaus media", "kaus media / meridionalis, purvashadha"),
#        ("kaCen", "ke kwan", "ke kwan"),
#        ("laGem", "kebash", "kebash, alkibash"),
#        ("omi-2Eri", "keid", "keid"),
#        ("beLup", "kekouan", "kekouan"),
#        ("taPeg", "kerb", "kerb, salm"),
#        ("kaDra", "ketu", "ketu"),
#        ("laVir", "khambalia", "khambalia"),
#        ("gaCom", "kissin", "kissin"),
#        ("alEqu", "kitalpha", "kitalpha"),
#        ("beUMi", "kochab", "kochab"),
#        ("beHer", "kornephoros", "kornephoros"),
#        ("beCrv", "kraz", "kraz"),
#        ("nu-1Dra", "kuma", "kuma (nu-1dra)"),
#        ("nu-2Dra", "kuma", "kuma (nu-2dra)"),
#        ("xiCep", "kurdah", "kurdah, alkurhah"),
#        ("zeCep", "kurhah", "kurhah"),
#        ("deCrt", "labrum", "labrum"),
#        ("muSer", "leiolepis", "leiolepis, leiolepidotus"),
#        ("upSco", "lesath", "lesath"),
#        ("xiAql", "libertas", "libertas"),
#        ("39Ari", "lilii borea", "lilii borea"),
#        ("dePsc", "linteum", "linteum"),
#        ("laCen", "ma ti", "ma ti, mati"),
#        ("epAur", "maaz", "maaz, almaaz, al anz"),
#        ("kaLyn", "mabsuthat", "mabsuthat"),
#        ("38Lyn", "maculosa", "maculosa, maculata"),
#        ("20Tau", "maia", "maia"),
#        ("omiSgr", "manubrium", "manubrium"),
#        ("zeCap", "marakk", "marakk"),
#        ("muCas", "marfak", "marfak"),
#        ("laOph", "marfik", "marfik"),
#        ("alPeg", "markab", "markab, purvabhadra"),
#        ("kaVel", "markeb", "markeb"),
#        ("kaHer", "marsik", "marsik marsic, marfik"),
#        ("laHer", "masym", "masym, maasym"),
#        ("etPeg", "matar", "matar"),
#        ("deHya", "mautinah", "mautinah"),
#        ("epGem", "mebsuta", "mebsuta"),
#        ("deUMa", "megrez", "megrez, atri"),
#        ("laOri", "meissa", "meissa, heka, mrgashirsha, mrigashirsha"),
#        ("zeGem", "mekbuda", "mekbuda"),
#        ("epCnc", "meleph", "meleph"),
#        ("muHer", "melkarth", "melkarth"),
#        ("beAur", "menkalinan", "menkalinan"),
#        ("alCet", "menkar", "menkar"),
#        ("laCet", "menkar", "menkar"),
#        ("thCen", "menkent", "menkent"),
#        ("xiPer", "menkib", "menkib"),
#        ("beUMa", "merak", "merak, pulaha"),
#        ("38Boo", "merga", "merga"),
#        ("23Tau", "merope", "merope"),
#        ("gaAri", "mesarthim", "mesarthim"),
#        ("M49", "messier 49", "messier 49"),
#        ("M87", "messier 87", "messier 87"),
#        ("beCar", "miaplacidus", "miaplacidus"),
#        ("beCru", "mimosa", "mimosa"),
#        ("epCrv", "minkar", "minkar"),
#        ("deOri", "mintaka", "mintaka, kumara"),
#        ("omiCet", "mira", "mira"),
#        ("beAnd", "mirach", "mirach"),
#        ("etPer", "miram", "miram"),
#        ("alPer", "mirfak", "mirfak, mirphak"),
#        ("beCMa", "mirzam", "mirzam, murzim, murzims"),
#        ("kaPer", "misam", "misam"),
#        ("zeUMa", "mizar", "mizar (miz0), vasishtha"),
#        ("etBoo", "mufrid", "mufrid, muphrid"),
#        ("gaCen", "muhlifain", "muhlifain"),
#        ("gaCMa", "muliphein", "muliphein, isis"),
#        ("omiUMa", "muscida", "muscida"),
#        ("18Del", "musica", "musica"),
#        ("thGem", "nageba", "nageba"),
#        ("phSgr", "nanto", "nanto"),
#        ("zePup", "naos", "naos, suhail hadar"),
#        ("gaCap", "nashira", "nashira"),
#        ("xiSer", "nehushtan", "nehushtan"),
#        ("beBoo", "nekkar", "nekkar"),
#        ("51And", "nembus", "nembus"),
#        ("beLep", "nihal", "nihal"),
#        ("zeDra", "nodus i", "nodus i, aldhibah"),
#        ("deDra", "nodus ii", "nodus ii, altais"),
#        ("epSer", "nulla pambu", "nulla pambu"),
#        ("siSgr", "nunki", "nunki, uttarashadha"),
#        ("beCrB", "nusakan", "nusakan"),
#        ("piCap", "oculus", "oculus"),
#        ("HD149026", "ogma", "ogma"),
#        ("M42", "orion nebula", "orion nebula, messier 42"),
#        ("psCap", "pazan", "pazan, pazhan"),
#        ("alPav", "peacock", "peacock"),
#        ("muVel", "peregrini", "peregrini, alherem"),
#        ("alCol", "phact", "phact"),
#        ("th-1Tau", "phaeo", "phaeo"),
#        ("th-2Tau", "phaesula", "phaesula, chamukuy"),
#        ("gaUMa", "phecda", "phecda, pulastya"),
#        ("gaUMi", "pherkad", "pherkad"),
#        ("11UMi", "pherkad minor", "pherkad minor"),
#        ("epCep", "phicares", "phicares, phicareus"),
#        ("deCet", "phycochroma", "phycochroma"),
#        ("mu-2Sco", "pipirima", "pipirima"),
#        ("28Tau", "pleione", "pleione"),
#        ("nuHya", "pleura", "pleura"),
#        ("alUMi", "polaris", "polaris"),
#        ("siOct", "polaris australis", "polaris australis"),
#        ("muSgr", "polis", "polis"),
#        ("beGem", "pollux", "pollux, punarvasu"),
#        ("gaVir", "porrima", "porrima"),
#        ("46LMi", "praecipua", "praecipua"),
#        ("M44", "praesepe cluster", "praesepe cluster"),
#        ("deAur", "prijipati", "prijipati"),
#        ("deBoo", "princeps", "princeps"),
#        ("alCMi", "procyon", "procyon"),
#        ("etGem", "propus", "propus (etagem)"),
#        ("ioGem", "propus iotgem", "propus (iotgem)"),
#        ("V645 Cen", "proxima centauri", "proxima centauri"),
#        ("deSer", "qin", "qin, chin"),
#        ("epEri", "ran", "ran"),
#        ("deEri", "rana", "rana"),
#        ("muVir", "ril alauva", "rijl al awwa, ril alauva, ras alauwa"),
#        ("alHer", "rasalgethi", "rasalgethi"),
#        ("alOph", "rasalhague", "rasalhague"),
#        ("alLeo", "regulus", "regulus, magha"),
#        ("zePsc", "revati", "revati (zepsc)"),
#        ("beOri", "rigel", "rigel"),
#        (
#            "alCen",
#            "rigil kentaurus",
#            "rigel kentaurus, toliman, bungula, proxima centauri",
#        ),
#        ("muVir", "rijl al awwa", "rijl al awwa, ril alauva"),
#        ("deBoo", "rotanev", "rotanev, dhanishtha, shravishtha"),
#        ("deCyg", "ruc", "ruc, rukh, urakhga, al fawaris"),
#        ("deCas", "ruchbah", "ruchbah, rucha"),
#        ("ome-1Cyg", "ruchbah i", "ruchbah i"),
#        ("ome-2Cyg", "ruchbah ii", "ruchbah ii"),
#        ("thHer", "rukbalgethi genubi", "rukbalgethi genubi"),
#        ("taHer", "rukbalgethi shemali", "rukbalgethi shemali"),
#        ("alSgr", "rukbat", "rukbat"),
#        ("zeHer", "rutilicus", "rutilicus"),
#        ("etOph", "sabik", "sabik"),
#        ("gaAqr", "sadalachbia", "sadalachbia, sadachbia"),
#        ("laPeg", "sadalbari", "sadalbari"),
#        ("alAqr", "sadalmelek", "sadalmelek, sadalmelik"),
#        ("beAqr", "sadalsuud", "sadalsuud"),
#        ("ze-1Aqr", "sadaltager", "sadaltager"),
#        ("gaCyg", "sador", "sador, sadir, sadr"),
#        ("kaOri", "saiph", "saiph"),
#        ("SN1987A", "sanduleak", "sanduleak"),
#        ("thSco", "sargas", "sargas"),
#        ("deHer", "sarin", "sarin"),
#        ("epLep", "sasin", "sasin"),
#        ("piHya", "sataghni", "sataghni"),
#        ("53Eri", "sceptrum", "sceptrum"),
#        ("bePeg", "scheat", "scheat"),
#        ("alCas", "schedar", "schedar, shedir, schedir"),
#        ("ioCar", "scutulum", "scutulum, tureis, aspidiske"),
#        ("piAqr", "seat", "seat"),
#        ("deTau", "secunda hyadum", "secunda hyadum (detau)"),
#        ("epCas", "segin", "segin"),
#        ("gaBoo", "seginus", "seginus, haris"),
#        ("etSgr", "sephdar", "sephdar, ira furoris"),
#        ("alSge", "sham", "sham"),
#        ("ACO3558", "shapley supercluster", "shapley supercluster, a3558"),
#        ("laSco", "shaula", "shaula, mula"),
#        ("beLyr", "sheliak", "sheliak"),
#        ("beAri", "sheratan", "sheratan, ashvini"),
#        ("rhLeo", "shir", "shir"),
#        ("siLeo", "shishimai", "shishimai"),
#        ("omeCar", "simiram", "simiram"),
#        ("gaPsc", "simmah", "simmah"),
#        ("nuOph", "sinistra", "sinistra"),
#        ("alCMa", "sirius", "sirius, lubdhaka"),
#        ("kaAqr", "situla", "situla"),
#        ("deAqr", "skat", "skat"),
#        ("etHer", "sofian", "sofian"),
#        ("alVir", "spica", "spica, citra"),
#        ("NGC6530", "spiculum", "spiculum"),
#        ("22Tau", "sterope ii", "sterope ii"),
#        ("alDel", "sualocin", "sualocin"),
#        ("omiLeo", "subra", "subra"),
#        ("ga-2Vel", "suhail al muhlif", "suhail al muhlif, regor"),
#        ("gaLyr", "sulaphat", "sulaphat, sulafat"),
#        ("ioVir", "syrma", "syrma"),
#        ("pi-3Ori", "tabit", "tabit (pi-3ori)"),
#        ("pi-4Ori", "tabit", "tabit (pi-4ori)"),
#        ("8Dra", "taiyi", "taiyi"),
#        ("ioUMa", "talitha", "talitha / borealis"),
#        ("kaUMa", "talitha australis", "talitha australis, alkaphrah"),
#        ("etSer", "tang", "tang"),
#        ("muUMa", "tania australis", "tania australis"),
#        ("laUMa", "tania borealis", "tania borealis"),
#        ("gaAql", "tarazed", "tarazed"),
#        ("19Tau", "taygeta", "taygeta"),
#        ("zeCnc", "tegmen", "tegmen, tegmine"),
#        ("muGem", "tejat", "tejat"),
#        ("omeSgr", "terebellium", "terebellium"),
#        ("upOri", "thabit", "thabit"),
#        ("taCrB", "blaze star", "blaze star"),
#        ("up-2Eri", "theemin", "theemin"),
#        ("alDra", "thuban", "thuban, dhruva"),
#        ("gaLup", "thusia", "thusia"),
#        ("7Dra", "tianyi", "tianyi"),
#        ("bePsA", "tien kang", "tien kang"),
#        ("HR4609", "tonatiuh", "tonatiuh"),
#        (
#            "omiPsc",
#            "torcularis septentrionalis",
#            "torcularis septentrionalis, torcular",
#        ),
#        ("th-1Ori", "trapezium", "trapezium"),
#        ("trappist-1", "trappist-1", "trappist-1"),
#        ("ioLeo", "tse tseng", "tse tseng, tsze tseang"),
#        ("thAql", "tseen foo", "tseen foo"),
#        ("phVel", "tseen ke", "tseen ke"),
#        ("gaCas", "tsih", "tsih, cih"),
#        ("laCol", "tsze", "tsze"),
#        ("rhPup", "turais", "turais, tureis"),
#        ("epDra", "tyl", "tyl"),
#        ("ta-1Hya", "ukdah", "ukdah / prima"),
#        ("ta-2Hya", "ukdah secunda", "ukdah / secunda"),
#        ("alSer", "unukalhai", "unukalhai, cor serpentis"),
#        ("siCMa", "unurgunite", "unurgunite"),
#        ("epUMi", "urodelus", "urodelus"),
#        ("xiTau", "ushakaron", "ushakaron"),
#        ("thCar", "vathorz posterior", "vathorz posterior"),
#        ("upCar", "vathorz prior", "vathorz prior"),
#        ("alLyr", "vega", "vega, abhijit"),
#        ("14And", "veritate", "veritate"),
#        ("omePsc", "vernalis", "vernalis"),
#        ("epVir", "vindemiatrix", "vindemiatrix"),
#        ("VC", "virgo cluster", "virgo cluster"),
#        ("io-1Lib", "vishakha", "vishakha"),
#        ("deGem", "wasat", "wasat"),
#        ("beCol", "wazn", "wazn"),
#        ("epSco", "wei", "wei, larawag"),
#        ("deCMa", "wezen", "wezen"),
#        ("zePhe", "wurren", "wurren"),
#        ("mu-1Sco", "xamidimura", "xamidimura"),
#        ("omiVel", "xestus", "xestus"),
#        ("laBoo", "xuange", "xuange"),
#        ("epOph", "yed posterior", "yed posterior"),
#        ("deOph", "yed prior", "yed prior"),
#        ("deUMi", "yildun", "yildun"),
#        ("etVir", "zaniah", "zaniah"),
#        ("gaEri", "zaurak", "zaurak"),
#        ("beVir", "zavijava", "zavijava, alaraph"),
#        ("up-1Hya", "zhang", "zhang"),
#        ("zeEri", "zibal", "zibal"),
#        ("deLeo", "zosma", "zosma, dhur, purvaphalguni"),
#        ("gaLib", "zubenelakrab", "zubenelakrab, zubenelhakrabi, zuben elakrab"),
#        ("deLib", "zubenelakribi", "zubenelakribi, zuben elakribi"),
#        ("al-2Lib", "zubenelgenubi", "zubenelgenubi, zuben elgenubi"),
#        ("beLib", "zubeneshamali", "zubeneshamali, zuben eschamali"),
#        ("nuLib", "zubenhakrabi", "zubenhakrabi, zuben hakrabi"),
#    ],
